# Verify Remote State Configuration Script
# This script verifies that all environment modules are using remote state correctly

param(
    [string]$Environment = "dev",
    [switch]$Help
)

# Show help if requested
if ($Help) {
    Write-Host @"
Remote State Verification Script

This script verifies that all environment modules are properly configured to use remote state.

Usage:
    .\verify-remote-state.ps1 [-Environment <env>] [-Help]

Parameters:
    -Environment      Environment to verify (default: dev)
    -Help            Show this help message

Examples:
    # Verify development environment
    .\verify-remote-state.ps1

    # Verify production environment
    .\verify-remote-state.ps1 -Environment prod
"@
    exit 0
}

# Set error action preference
$ErrorActionPreference = "Stop"

# Function to write colored output
function Write-ColorOutput {
    param(
        [string]$Message,
        [string]$Color = "White"
    )
    Write-Host $Message -ForegroundColor $Color
}

# Function to check if command exists
function Test-Command {
    param([string]$Command)
    try {
        Get-Command $Command -ErrorAction Stop | Out-Null
        return $true
    } catch {
        return $false
    }
}

# Function to check prerequisites
function Test-Prerequisites {
    Write-ColorOutput "Checking prerequisites..." "Yellow"
    
    # Check if Terragrunt is installed
    if (-not (Test-Command "terragrunt")) {
        Write-ColorOutput "ERROR: Terragrunt is not installed or not in PATH" "Red"
        Write-ColorOutput "Please install Terragrunt from: https://terragrunt.gruntwork.io/docs/getting-started/install/" "Red"
        exit 1
    }
    
    # Check if AWS CLI is installed
    if (-not (Test-Command "aws")) {
        Write-ColorOutput "ERROR: AWS CLI is not installed or not in PATH" "Red"
        Write-ColorOutput "Please install AWS CLI from: https://aws.amazon.com/cli/" "Red"
        exit 1
    }
    
    # Check if AWS credentials are configured
    try {
        $awsIdentity = aws sts get-caller-identity 2>$null | ConvertFrom-Json
        if (-not $awsIdentity.Account) {
            throw "No AWS credentials configured"
        }
        Write-ColorOutput "Using AWS Account: $($awsIdentity.Account)" "Green"
    } catch {
        Write-ColorOutput "ERROR: AWS credentials not configured or invalid" "Red"
        Write-ColorOutput "Please run 'aws configure' to set up your credentials" "Red"
        exit 1
    }
    
    Write-ColorOutput "All prerequisites met!" "Green"
}

# Function to verify module configuration
function Test-ModuleConfiguration {
    param(
        [string]$ModulePath,
        [string]$ModuleName
    )
    
    Write-ColorOutput "  Checking $ModuleName..." "White"
    
    # Check if terragrunt.hcl exists
    $terragruntFile = Join-Path $ModulePath "terragrunt.hcl"
    if (-not (Test-Path $terragruntFile)) {
        Write-ColorOutput "    ❌ No terragrunt.hcl found" "Red"
        return $false
    }
    
    # Check if backend.tf exists (generated by Terragrunt)
    $backendFile = Join-Path $ModulePath "backend.tf"
    if (-not (Test-Path $backendFile)) {
        Write-ColorOutput "    ⚠️  No backend.tf found - run 'terragrunt init' first" "Yellow"
        return $false
    }
    
    # Check backend.tf content for S3 backend
    $backendContent = Get-Content $backendFile -Raw
    if ($backendContent -match "backend.*s3") {
        Write-ColorOutput "    ✅ S3 backend configured" "Green"
        return $true
    } else {
        Write-ColorOutput "    ❌ S3 backend not configured" "Red"
        return $false
    }
}

# Function to verify environment
function Test-Environment {
    param([string]$Environment)
    
    $envPath = "environments/$Environment"
    
    if (-not (Test-Path $envPath)) {
        Write-ColorOutput "ERROR: Environment path not found: $envPath" "Red"
        return $false
    }
    
    Write-ColorOutput "Verifying environment: $Environment" "Cyan"
    Write-ColorOutput "Path: $envPath" "White"
    Write-ColorOutput ""
    
    # Check environment-level terragrunt.hcl
    Write-ColorOutput "Checking environment configuration..." "Yellow"
    $envTerragruntFile = Join-Path $envPath "terragrunt.hcl"
    if (Test-Path $envTerragruntFile) {
        $envContent = Get-Content $envTerragruntFile -Raw
        if ($envContent -match "include.*root") {
            Write-ColorOutput "  ✅ Root configuration included" "Green"
        } else {
            Write-ColorOutput "  ❌ Root configuration not included" "Red"
            return $false
        }
    } else {
        Write-ColorOutput "  ❌ No environment terragrunt.hcl found" "Red"
        return $false
    }
    
    # Check individual modules
    Write-ColorOutput "" "White"
    Write-ColorOutput "Checking individual modules..." "Yellow"
    
    $modules = @(
        @{ Path = "cognito"; Name = "Cognito" },
        @{ Path = "s3-website"; Name = "S3 Website" },
        @{ Path = "s3-content"; Name = "S3 Content" },
        @{ Path = "cloudfront"; Name = "CloudFront" },
        @{ Path = "route53-acm"; Name = "Route53 & ACM" },
        @{ Path = "monitoring"; Name = "Monitoring" }
    )
    
    $allModulesValid = $true
    
    foreach ($module in $modules) {
        $modulePath = Join-Path $envPath $module.Path
        if (Test-Path $modulePath) {
            $moduleValid = Test-ModuleConfiguration -ModulePath $modulePath -ModuleName $module.Name
            if (-not $moduleValid) {
                $allModulesValid = $false
            }
        } else {
            Write-ColorOutput "  ⚠️  Module $($module.Name) not found (skipping)" "Yellow"
        }
    }
    
    return $allModulesValid
}

# Function to show verification summary
function Show-VerificationSummary {
    param([string]$Environment, [bool]$IsValid)
    
    Write-ColorOutput "" "White"
    Write-ColorOutput "=== Verification Summary ===" "Cyan"
    Write-ColorOutput "Environment: $Environment" "White"
    
    if ($IsValid) {
        Write-ColorOutput "Status: ✅ All modules properly configured for remote state" "Green"
        Write-ColorOutput "" "White"
        Write-ColorOutput "Next Steps:" "Yellow"
        Write-ColorOutput "1. Run 'terragrunt init' in each module directory if not done already" "White"
        Write-ColorOutput "2. Run 'terragrunt plan' to verify remote state connection" "White"
        Write-ColorOutput "3. Deploy your infrastructure using remote state" "White"
    } else {
        Write-ColorOutput "Status: ❌ Configuration issues found" "Red"
        Write-ColorOutput "" "White"
        Write-ColorOutput "Issues to Fix:" "Yellow"
        Write-ColorOutput "1. Ensure environment terragrunt.hcl includes root configuration" "White"
        Write-ColorOutput "2. Run 'terragrunt init' in module directories" "White"
        Write-ColorOutput "3. Verify S3 bucket and DynamoDB table exist" "White"
        Write-ColorOutput "4. Check AWS credentials and permissions" "White"
    }
    
    Write-ColorOutput "" "White"
    Write-ColorOutput "For more information, see the bootstrap/README.md file" "Cyan"
}

# Main execution
try {
    Write-ColorOutput "=== Remote State Configuration Verification ===" "Cyan"
    Write-ColorOutput "Environment: $Environment" "White"
    Write-ColorOutput ""
    
    # Check prerequisites
    Test-Prerequisites
    
    # Verify environment
    $isValid = Test-Environment -Environment $Environment
    
    # Show summary
    Show-VerificationSummary -Environment $Environment -IsValid $isValid
    
    # Exit with appropriate code
    if ($isValid) {
        exit 0
    } else {
        exit 1
    }
    
} catch {
    Write-ColorOutput "ERROR: Script execution failed: $($_.Exception.Message)" "Red"
    exit 1
}
